name: Benchmark Enzyme VS React Testing Library

on:
  push:
    branches:
      - master

jobs:
  enzyme-rtl-benchmarks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elements: [1, 100, 1000, 10000]
    steps:
      - uses: actions/checkout@v2
      - run: yarn install

      - name: "Test with ${{ matrix.elements }} elements"
        run: yarn test
        env:
          FORM_EL_COUNT: ${{ matrix.elements }}
